"""
Configuration module for the embedding system.
"""

from .settings import (
    MAX_TOKENS,
    AVG_WORDS_PER_TOKEN,
    MAX_WORDS,
    MONGO_URI,
    DATABASE_NAME,
    EMBEDDING_MODEL,
    JINA4_MODEL_NAME,
    JINA4_MAX_SEQ_LENGTH,
    QWEN3_MODEL_NAME,
    QWEN3_MAX_SEQ_LENGTH,
    OPENAI_MODEL_NAME,
    OPENAI_MAX_SEQ_LENGTH,
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_DELAY,
)

__all__ = [
    "MAX_TOKENS",
    "AVG_WORDS_PER_TOKEN", 
    "MAX_WORDS",
    "MONGO_URI",
    "DATABASE_NAME",
    "EMBEDDING_MODEL",
    "JINA4_MODEL_NAME",
    "JINA4_MAX_SEQ_LENGTH",
    "QWEN3_MODEL_NAME",
    "QWEN3_MAX_SEQ_LENGTH",
    "OPENAI_MODEL_NAME",
    "OPENAI_MAX_SEQ_LENGTH",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_RETRY_DELAY",
]
